const contactsTypes = {
  FETCH_CONTACTS: 'FETCH_CONTACTS',
  FETCH_DUMMY_CONTACTS: 'FETCH_DUMMY_CONTACTS',
  FETCH_REQUEST: 'FETCH_REQUEST',
  ADD_CONTACT: 'ADD_CONTACT',
  HANDLE_CONTACT_TO_FAVORITES: 'HANDLE_CONTACT_TO_FAVORITES',
  FILTER_LIST_BY_TYPE: 'FILTER_LIST_BY_TYPE',
  SHOW_FILTERED_RESULTS: 'SHOW_FILTERED_RESULTS',
};

export default contactsTypes;
