const TasksTypes = {
  FETCH_TASKS: 'FETCH_TASKS',
  FETCH_DUMMY_TASKS: 'FETCH_DUMMY_CONTACTS',
  FETCH_REQUEST: 'FETCH_REQUEST',
  ADD_TASK: 'ADD_TASK',
  TOGGLE_TASK_COMPLETED: 'TOGGLE_TASK_COMPLETED',
  TOGGLE_ADDED_TASK: 'TOGGLE_ADDED_TASK',
};

export default TasksTypes;
