const userTypes = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
};

export default userTypes;
